# Generated by Django 3.0.5 on 2020-04-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genomics', '0003_auto_20200425_0545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenomicsUsers',
        ),
    ]
